### ISSUE TITLE
As a teacher I want my students to be able to use a five point scale to rate their emotional state so that I or other faculty may be able to assess the emotional state of my students.

### ISSUE THREAD

**Issue by jschwarzwalder** [TeamBlue-IT355/emotion-counts#11]
- [x] Design UI to represent 5 point scale for emotional state #31 Jami
- [x] When student hits submit, then their submission should be sent to teacher #33
- [x] Test that selecting each value translates to different score when hitting submit #34
- [x] Usability test that the interface is kid friendly #35 Jami

Acceptance Criteria

Given that I am a student, when I get a question that I need to enter my emotional state on a 5 point scale, then I am able to easily select my emotion from the given scale.

Given that I am a student, when I get am asked my emotional state, then I know what each of the 5 points should represent

Given that I am a teacher, when a student answers a survey question, then I should be able to access a value that represents the students emotional state.
