### ISSUE TITLE
As a teacher I want my students to be able to take the survey on a website that is kid friendly so that the students have a positive experience while taking the survey.

### ISSUE THREAD

**Issue by jschwarzwalder** [TeamBlue-IT355/emotion-counts#12]
- [x] Build Paper Prototype to explore options for kid friendly UI #26  - Jami
- [x] Perform Usability test with potential students to ensure answering questions is easy to do. #25 - Jami
- [x] Create a single PHP Website for questions #15 Josh
- [x] add questions #18  Josh
- [x] add form boxes for name and questions #19
- [x] add radial buttons #17 Ben
- [x] add a text box #20  Josh
- [x] add a submit button #16  Satinder 
- [x] create a function that sends submission to teacher's email with test results #21 
- [x] create a function that checks for questions that have not been answered except the text box open ended question #22 
- [x] Test that students answers are submitted via email #23 
- [x] Test to ensure all questions are required to be answered before emailing teacher #24

**Comment by jschwarzwalder** [comment]
Acceptance criteria

the site has all questions
the student is able to give an answer to all questions
the site checks for unanswered questions
the teacher receives an email of the student's results when the student submits their survey

**Comment by jschwarzwalder** [comment]
I feel like we should add Bootstrap Styles to this as well.
