### ISSUE TITLE
As a student I want to input my answers to the survey on a technical device so that my teacher and counselor can have my responses

### ISSUE THREAD

**Issue by jschwarzwalder** [TeamBlue-IT355/emotion-counts#2]
Tasks
- [x] On survey form submit, results are validated. #27
- [x] On submit, generate email to send results to teacher email #21 
- [x] Email should include student name, and  results #29
- [x] Test code with dummy results and personal email #30

**Comment by baarnold** [comment]
Acceptance Criteria
GIVEN that a teacher wants to see the results of a survey
WHEN the student submits their answers
THEN the teacher can see the results

**Comment by baarnold** [comment]
Tasks
On survey form submit, results are calculated.
On submit, generate email to send calculated results to teacher email
Email should include student name, time stamp, tallied results
Test code with dummy results and personal email

**Comment by Satinderk** [comment]
Acceptance criteria

Given a form to the students, so they can submit their answers , I am able to see their results.

Tasks

- Create a form with emotional faces with radio buttons
- we can save their results in the database.


Thank you.

Satinder kaur

Get Outlook for Android<https://aka.ms/ghei36>



On Wed, Jun 29, 2016 at 9:07 PM -0700, "Benjamin Arnold" <notifications@github.com<mailto:notifications@github.com>> wrote:


Tasks
On survey form submit, results are calculated.
On submit, generate email to send calculated results to teacher email
Email should include student name, time stamp, tallied results
Test code with dummy results and personal email

-
